### ISSUE TITLE
Поиск отсутствующих элементов массива

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#11]
Есть два массива с числами.
Массивы задаются на форме обработки. Размеры массивов могут быть разными.

Нужно найти и сообщить пользователю все элементы первого массива, которых нет во втором массиве.

**Comment by Ilyanski** [comment]
Задачу выполнил.

**Comment by nmivan** [comment]
Возвращайся к предыдущей. Теперь должно стать понятнее, как ее решать.

**Comment by nmivan** [comment]
Не закрывай, пока я не проверю.
