### ISSUE TITLE
Отчет по остаткам номенклатуры

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#12]
Сделать отчет, который выведет всю номенклатуру, которая есть в справочнике, и по каждой из них напишет остаток по всем складам одной цифрой.
Если остатка нет, надо написать ноль.

**Comment by Ilyanski** [comment]
Задачу выполнил, долго разбирался с пустыми строками в отчете. В запросе отчета, сделал Справочник "Номенклатура" основным, и левым соединением сделал Регистр. Сделал в ручную без конструктора, что то у меня с конструкторами не идет...

**Comment by nmivan** [comment]
Вставь сюда текст запроса.

**Comment by Ilyanski** [comment]
ВЫБРАТЬ
	Неменклатура.Наименование КАК Наименование,
	ТоварыНаСкладеОстатки.Склад КАК Склад,
	ЕСТЬNULL(ТоварыНаСкладеОстатки.КоличествоОстаток, 0) КАК КоличествоОстаток
ИЗ
	Справочник.Неменклатура КАК Неменклатура 
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрНакопления.ТоварыНаСкладе.Остатки КАК ТоварыНаСкладеОстатки
		ПО ТоварыНаСкладеОстатки.Номенклатура = Неменклатура.Ссылка

**Comment by nmivan** [comment]
Запрос сам писал?

**Comment by nmivan** [comment]
Аллё

**Comment by Ilyanski** [comment]
В конструкторе писал, просто поменял местами в ручную Справочник.Неменклатура с РегистрНакопления.ТоварыНаСкладе, что бы Левым соединением стал Регистр, и нул сам написал.
