### ISSUE TITLE
Цены номенклатуры

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#13]
1. Создать документ "Установка цен". В его табличной части - номенклатура и цена.
2. Добавить регистр сведений "Цены номенклатуры", подчиненный документу "Установка цен", периодичность День. Измерение - номенклатура, ресурс Цена.
3. Соответственно, написать проведение документа по регистру.
4. Сделать отчет "Цены номенклатуры", который показывает всю номенклатуру и ее цены на выбранную дату. Дата выбирается в форме отчета.

**Comment by Ilyanski** [comment]
ВЫБРАТЬ
	ЦеныНоменклатурыСрезПоследних.Номеклатура КАК Номеклатура,
	ЦеныНоменклатурыСрезПоследних.Цена КАК Цена
ИЗ
	РегистрСведений.ЦеныНоменклатуры.СрезПоследних КАК ЦеныНоменклатурыСрезПоследних

**Comment by Ilyanski** [comment]
ВЫБРАТЬ
	ЦеныНоменклатурыСрезПоследних.Цена КАК Цена,
	Неменклатура.Наименование КАК Наименование
ИЗ
	Справочник.Неменклатура КАК Неменклатура
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.ЦеныНоменклатуры.СрезПоследних КАК ЦеныНоменклатурыСрезПоследних
		ПО ЦеныНоменклатурыСрезПоследних.Номеклатура = Неменклатура.Ссылка

**Comment by Ilyanski** [comment]
ВЫБРАТЬ
	ЦеныНоменклатурыСрезПоследних.Цена КАК Цена,
	Неменклатура.Ссылка КАК Ссылка
ИЗ
	Справочник.Неменклатура КАК Неменклатура
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.ЦеныНоменклатуры.СрезПоследних КАК ЦеныНоменклатурыСрезПоследних
		ПО (ЦеныНоменклатурыСрезПоследних.Номеклатура = Неменклатура.Ссылка)

**Comment by Ilyanski** [comment]
ВЫБРАТЬ
	ЕСТЬNULL(ЦеныНоменклатурыСрезПоследних.Цена, 0) КАК Цена,
	Неменклатура.Ссылка КАК Ссылка
ИЗ
	Справочник.Неменклатура КАК Неменклатура
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.ЦеныНоменклатуры.СрезПоследних КАК ЦеныНоменклатурыСрезПоследних
		ПО (ЦеныНоменклатурыСрезПоследних.Номеклатура = Неменклатура.Ссылка)
