### ISSUE TITLE
Отчет с ценами и остатками

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#14]
Сделать отчет, который выводит всю номенклатуру, к каждой номенклатуре - общий остаток по всем складам, к каждой номенклатуре - ее текущую цену.

**Comment by Ilyanski** [comment]
ВЫБРАТЬ
	Неменклатура.Ссылка КАК Ссылка,
	ЕСТЬNULL(ТоварыНаСкладеОстатки.КоличествоОстаток, 0) КАК КоличествоОстаток,
	ЕСТЬNULL(ЦеныНоменклатурыСрезПоследних.Цена, 0) КАК Цена
ИЗ
	Справочник.Неменклатура КАК Неменклатура
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрНакопления.ТоварыНаСкладе.Остатки КАК ТоварыНаСкладеОстатки
		ПО ТоварыНаСкладеОстатки.Номенклатура = Неменклатура.Ссылка
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.ЦеныНоменклатуры.СрезПоследних КАК ЦеныНоменклатурыСрезПоследних
		ПО ЦеныНоменклатурыСрезПоследних.Номеклатура = Неменклатура.Ссылка
