### ISSUE TITLE
Заполнение документа по остаткам

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#16]
1. Добавить в документы Расход и Перемещение кнопку "Заполнить по остаткам".
2. При нажатии на кнопку табличная часть товаров очищается, и заполняется всеми номенклатурами, по которым есть положительный остаток на складе, который указан в шапке документа;
3. Остатки должны браться на дату документа;
4. Если склад в шапке не указан, то должны заполниться остатки по всем складам;
3. Количество в табличной части по каждой номенклатуре должно стать равным остатку на складе.

**Comment by Ilyanski** [comment]
Для Работы Дома 
[19.10.17.zip](https://github.com/nmivan/Ilya_learning/files/1398054/19.10.17.zip)

**Comment by nmivan** [comment]
Илья, как дела по задаче?

**Comment by Ilyanski** [comment]
Не получается сделать запрос правильный, выбрать вообще всю номенклатуру получается, не выходит отсеять номенклатуру где КоличествоОстаток = 0, в Условиях я так понял это делается, в интернете ничего путного найти не получается.  Запрос выгружаю в ТЗ, Команда у меня передает форму в функцию на сервер, и на сервере я уже буду форму изменять. Но пока что вот, с запросом ступор какой то,

**Comment by nmivan** [comment]
тебе надо не отсеять номенклатуру с нулевым остатком, а выбрать номенклатуру с положительным остатком. В условиях запроса пишется не то, что ты хочешь убрать, а то, что ты хочешь получить.

**Comment by Ilyanski** [comment]
Ну я пенек в общем, сб, вс, не отдыхал, а вот пятницу конкретно просрал можно сказать, запрос выдающий нужную номенклатуру есть. Сейчас соображу как форму на сервере изменить и задачу выполню.

**Comment by nmivan** [comment]
Как дела? Получилось?

**Comment by Ilyanski** [comment]
скорее нет, чем да, я сейчас один тут, может уже на завтра отложу. Если в интернете пример не найду.

**Comment by nmivan** [comment]
пример чего ты хочешь в интернете найти?

**Comment by Ilyanski** [comment]
я даже сформулировать толком не могу, у меня есть запрос, есть ТЗ, мне нужно передать это в управляемую форму. Саму форму я уже передал в функцию как "ЭтотОбъект"

**Comment by nmivan** [comment]
как ты тогда ищешь, если вопроса не знаешь.

ЭтотОбъект - это не форма, а документ, для которого открыта форма.
Можно менять ЭтотОбъект в общем модуле, но это не очень хорошо.
Можно вернуть ТЗ в форму, и там провести изменения объекта.
Вариантов масса.

**Comment by Ilyanski** [comment]
Ну я могу вернуть ТЗ в форму, но не представляю как строки из ТЗ или Запроса отобразить в документе. Какой мне для этого метод нужен, или как правильно назвать это операцию. Ну или хотя бы сформулировать, что бы я нужную информацию в гугле нашел.

**Comment by nmivan** [comment]
тебе надо заполнить табличную часть документа.
Раньше ты решал подобную задачу, когда добавлял строки в таблицу на форме.
Можно добавлять по одной строке и заполнять строками ТЗ.
Можно загрузить табличную часть из ТЗ, если имена колонок совпадают.
