### ISSUE TITLE
Долги по отгрузкам

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#18]
Придумать и сделать так, чтобы система давала ответ на вопрос: какие отгрузки нам клиенты оплатили, а какие нет.
Отгрузка у тебя - документ Расход.
Оплата от клиента тоже есть, не помню название документа.

**Comment by Ilyanski** [comment]
Добавил к Регистру Взаиморасчеты Измерение : ДокументРасчета тип: ДокументСсылка.Расход
Добавил к Документу ОплатаОтПокупателя Реквизит: ДокументРасчета тип: ДокументСсылка.Расход
Документ Расход добавил к движению регистра ссылку на самого себя в Измерение ДокументРасчета.
При ОплатаОтПокупателя нужно указать документ расхода для которого производиться оплата.  
В отчете по Взаиморасчетам добавил измерение ДокументРасчета, он стал выводить сумма прихода и расхода и конченый остаток по каждому документу, подводя итог под контрагента и общий. Если что отчет Взаиморасчеты(Вариант) там их несколько... На сегодня закончил.

**Comment by unpete** [comment]
Помогал, и он обещал взять у тебя следующую задачу похожего плана, чтобы прорешать самостоятельно.

**Comment by nmivan** [comment]
Снижаю оценку до 5. Смысл задачи был в том, чтобы Илья сам придумал решение.
