### ISSUE TITLE
Найти книгу

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#2]
Фокс А., Фокс Д. Бейсик для всех: Курс программирования на языке Бейсик для начинающих.

**Comment by nmivan** [comment]
Как дела, @Ilyanski ? Нашел книгу?

**Comment by Ilyanski** [comment]
@nmivan , книгу найти не получается, надо спрашивать на тематических форумах. Если книга точно откроет мне глаза, то можно будет и купить ее с рук. Думаю задачу можно закрыть, подумать на следующей практической задачей, и вообще обсудить мой застой.

**Comment by nmivan** [comment]
Нет, задачу закрывать не будем, книгу надо найти.
Это и есть преодоление застоя - решение конкретной задачи.
Давай, не унывай.

**Comment by Ilyanski** [comment]
Потерял почти все надежды найти электронный вариант. На форумах помочь тоже не могут, возьму книгу в публичной библиотеке.

**Comment by nmivan** [comment]
Илья, чем кончилась история с книгой?

**Comment by Ilyanski** [comment]
Кончилась полнейшим безрассудством, завтра пойду за ней после обеда.

**Comment by nmivan** [comment]
Илья, чем кончилась история с книгой?

**Comment by nmivan** [comment]
Закрываю, надоела эта задача.
