### ISSUE TITLE
Процент оплаты отгрузок

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#20]
Нужно сделать так, чтобы в форме списка отгрузок отображался процент оплаты для каждого документа - по тем контрагентам, для которых ведется учет по расчетам.

**Comment by Ilyanski** [comment]
не успел доделать, чет тяжко у меня пошла задача с самого начала. Создал реквизит Сумма, он высчитывает сумму перед записью в Расходе, буду обращаться в ДинСписке к нему.  В целом доволен днем, вспомнил все что тогда делал, осталось немного, завтра рассчитываю утром сделать.

**Comment by nmivan** [comment]
Ты не в ту сторону пошел.

**Comment by Ilyanski** [comment]
А почему, в итоге ведь в форме списка будет колонка с процентами оплаты у соответствующих контрагентов.

**Comment by nmivan** [comment]
Для этого не нужен реквизит Сумма документа. Вся информация уже есть в регистре.

**Comment by Ilyanski** [comment]
Ну раньше я хотел воспользоваться той суммой, что находиться в табличной части документа, еще Евгений сказал что Регистр не правильно работает, он делает запись документа по каждой строке номенклатуры в Табличной части и это не правильно, я так понял это из за цикла в обработке проведения

**Comment by Ilyanski** [comment]
Все в форме списка Расхода, появилась колонка в которой есть процент оплаты документа для соответствующих контрагентов. Для контрагентов без расчета в Условном Оформлении с условием что реквизит Контрагент.ПоРасчету = Ложь выводит Текст:"нет данных"
Что бы не было путаницы модифицировал запрос в Динсписке:
Когда создали пустой документ отгрузки, и остатки isnull тогда будет писать 0.
Когда создали пустой документ, и по нему прошла оплата создав там отрицательный остаток, тогда пишет: "Оплата без отгрузки"
Я решил оставить Реквизит: СуммаДокумента, потому что нашел его очень полезным, с его помощью я:
Переделал Регистр накопления Взаиморасчеты, в свое время конструктором запроса был создан сомнительный код, который шел циклом по каждой строке документа, использовал 1)ТекСтрокуТабличнойЧасти.Сумма = Сумма, вместо этой суммы я подставил "СуммаДокумента", ну и цикл бесполезный убрал. 
2)В запросе ДинСписка мне стало понятно как обратиться к Сумме документа.  
[12.11.2017.zip](https://github.com/nmivan/Ilya_learning/files/1465916/12.11.2017.zip)

**Comment by nmivan** [comment]
Если делал сам, то отлично.
