### ISSUE TITLE
Заполнение оплаты остатками долгов

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#21]
Надо сделать так, чтобы в документах оплаты (входящих и исходящих) появилась кнопка, которая вычислит сумму долга по контрагенту и подставит ее в платежку.
Если контрагент по расчетам, то сумма должна браться по указанному в платежке документу.
Если не по расчетам, то просто сумма долга.

**Comment by Ilyanski** [comment]
К сожалению успел 20 минуток посидеть только, что начал:
В общем модуле сделал процедуру с запросом, и вывел Остаток через переданный Объект. Завтра продолжу работу, уже есть идеи как сделать все вариативным. Вот если интересно конф. кнопка сделана в ОплатеОтПокупателя, пока что выводит сумму долга в случае если указать Контрагента и Документ. 
[13.11.17.zip](https://github.com/nmivan/Ilya_learning/files/1466602/13.11.17.zip)

**Comment by Ilyanski** [comment]
Передаю в общий модуль Объект командой.
Сделал в Общем модуле 2 Если: 
первое если Объект.Контрагент.ПоРасчету = Истина, Запрос: ВзаиморасчетыОстатки.СуммаОстаток Параметр:  ДокументРасчета
второй Если = Ложь,  Запрос: ВзаиморасчетыОстатки.СуммаОстаток Параметр:  Контрагент
Если пойдет то можно следующее задание выдавать, но скорее всего я это еще доделаю, новое только вечером начну или завтра уже. 
[14.11.17.zip](https://github.com/nmivan/Ilya_learning/files/1469884/14.11.17.zip)

**Comment by nmivan** [comment]
сойдет
