### ISSUE TITLE
Ввод на основании

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#23]
Сделать так, чтобы на основании документа Приход можно было ввести документ оплаты поставщику, а на основании документа Расход можно было ввести документ оплата от покупателя.
При вводе на основании должна рассчитываться сумма платежа - остаток долга (либо по документу прихода/расхода, либо общая сумма долга, если не по расчетам контрагент работает).

**Comment by Ilyanski** [comment]
А что должно произойти если нажать на не проведенный документ? 
Сделал часть с расходом, осталось на приход присобачить, нужно идти, доделаю завтра утром.

**Comment by Ilyanski** [comment]
Сделал. 
Создавал запросы в каждом объекте внутри Обработки заполнения, в качестве параметров выступили Данные заполнения. 
Проблему с расчетными контрагентами сначала решил просто двумя Запросами через Если, потом  решил сделать все через один Запрос с Если на установке параметров, получаю либо пустую ссылку как параметр, либо обычные ДанныеЗаполнения.Ссылка. 
[16.11.17.zip](https://github.com/nmivan/Ilya_learning/files/1477545/16.11.17.zip)
