### ISSUE TITLE
Учет стоимости по средней

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#24]
1. добавить регистр накопления СтоимостьТоваров. Состав измерений такой же, как в регистре товаров, только добавляется ресурс Стоимость;
2. При приходе стоимость каждой позиции равна стоимости из документа;
3. При расходе стоимость позиции в регистре определяется, как средняя цена умножить на количество.

Например, есть два прихода одной и той же номенклатуры, 1 шт по 10 рублей и 1 шт по 20 рублей. Если после этого сделать расход 1 шт, то ее стоимость должна быть равна 15 рублей.

4. При перемещении стоимость расходного движения определяется так же, как для расхода, а в приходном движении ставится та же стоимость, что и в расходном.
5. Отключить контроль остатков товаров при проведении документов. Оставить выдачу предупреждения, но не останавливать проведение. В товарном регистре будет возникать отрицательный остаток - ничего страшного.
6. Если по регистру СтоимостьТоваров списывается количество больше, чем есть на остатке, то движение должно сформироваться с тем количеством, которое есть на остатке.

Например, на остатке 2 шт, а в документе расхода указано 5 шт. В регистре должна быть запись на списание 2 шт.

7. Сделать отчет по стоимости товаров, который покажет начальные остатки, приход, расход и конечные остатки по количеству и стоимости.

**Comment by Ilyanski** [comment]
Создал запрос который возвращает мне остатки количества и стоимости из Регистра "СтоимостьТоваров", и еще табличную часть документа, поля: Количество и Номенклатура. 
Установил 2 параметра:
1) РасходТовары.Ссылка = ссылка, что бы резать по текущему документу. 
2) Склад = склад, что бы показывал среднюю по складам. 
Само движение происходит по Результату запроса, и арифметика среднего числа тоже там в движениях. Сейчас приступлю к Перемещению Товаров.

**Comment by Ilyanski** [comment]
Я чет прикинул, запрос то тот же самый, передам в общий модуль ссылку и склады, и там размещу запрос, что бы не дублировать.

**Comment by nmivan** [comment]
> и еще табличную часть документа, поля: Количество и Номенклатура.

это зачем? Метаданные документа не должны измениться.

**Comment by Ilyanski** [comment]
А они и не меняют, просто что бы были в Результате. 
"ВЫБРАТЬ
		                      |	СтоимостьТоваровОстатки.КоличествоОстаток КАК КоличествоОстаток,
		                      |	СтоимостьТоваровОстатки.СтоимостьОстаток КАК СтоимостьОстаток,
		                      |	РасходТовары.Номенклатура КАК Номенклатура,
		                      |	РасходТовары.Количество КАК Количество
		                      |ИЗ
		                      |	Документ.Расход.Товары КАК РасходТовары
		                      |		ЛЕВОЕ СОЕДИНЕНИЕ РегистрНакопления.СтоимостьТоваров.Остатки(, Склад = &Склад) КАК СтоимостьТоваровОстатки
		                      |		ПО РасходТовары.Номенклатура = СтоимостьТоваровОстатки.Номенклатура
		                      |ГДЕ
		                      |	РасходТовары.Ссылка = &Ссылка";

**Comment by nmivan** [comment]
Илья, как дела?

**Comment by Ilyanski** [comment]
Создал запрос который возвращает мне остатки количества и стоимости из Регистра "СтоимостьТоваров", и еще табличную часть документа, поля: Количество и Номенклатура.
Связь по номенклатурам, левое соединение.
Установил 3 параметра:

1)РасходТовары.Ссылка = ссылка, что бы резать по текущему документу.
2)Склад = склад, что бы показывал среднюю по складам.
3)Товары.Номенклатура <> NULL, что бы Оплата без отгрузки не записывалась в движениях, из за пустого результата запроса.  

Движения пишутся с Цикла по ТаблицеЗначений с результатом запроса, в цикле движений расхода созданы 2 Если:
1) Первое Если выбирает какое количество использовать в зависимости от того хватает ли Остатков. 
2) Второе Если выбирает высчитывать стоимость или оставить как есть, потому что придется расходовать все Остаточное количество и средняя уже высчитана грубо говоря. 
 
Вроде бы все, задача большая постоянно кажется что упустил что то, даже если так, уже работает я считаю можно проверить, указать на что то. 
[21.11.17.zip](https://github.com/nmivan/Ilya_learning/files/1490661/21.11.17.zip)

**Comment by nmivan** [comment]
1. Остатки стоимости у тебя берутся не на дату документа, а на текущую дату;
2. `Товары.Номенклатура <> NULL` - хрень какая-то непонятная. Причем тут оплата вообще?;
3. неправильно сделаны приходные движения в перемещении. Они должны быть равны расходным. Сколько уходит со склада-отправителя, столько приходит на склад-получатель, по количеству и стоимости;
4. Отчет неправильный. Там не нужны детальные записи. И ресурсов должно быть больше.

**Comment by Ilyanski** [comment]
![image](https://user-images.githubusercontent.com/28789104/33115877-6fe55d2e-cf84-11e7-9640-af0ec6690920.png)
![image](https://user-images.githubusercontent.com/28789104/33115888-812ff148-cf84-11e7-9118-8f44b2feb462.png)
вот так должно быть?

**Comment by nmivan** [comment]
Почти. Не должно быть детальных записей в группировках, и синих полей в "Выбранных полях".

**Comment by Ilyanski** [comment]
![image](https://user-images.githubusercontent.com/28789104/33119037-88a0212c-cf8f-11e7-8c11-cff90dc958e7.png)
![image](https://user-images.githubusercontent.com/28789104/33119056-9ad401b0-cf8f-11e7-9632-bec027401110.png)
Вот так получилось, верное направление? не понимаю как этот дубль убрать.

**Comment by nmivan** [comment]
На группировки смотри, у тебя там детальные записи остались. А номенклатуру ты зря убрал из запроса. Она должна быть группировкой, как и склад.

**Comment by Ilyanski** [comment]
![image](https://user-images.githubusercontent.com/28789104/33123691-a7b76a4a-cf9c-11e7-8fb0-3fab7360956b.png)
![image](https://user-images.githubusercontent.com/28789104/33123717-bab984ca-cf9c-11e7-972a-9992a45769ff.png)
Вроде бы, все детальные записи убраны, а выглядит отчет так же по меому как и до этого, периода нету, добавлю.

**Comment by nmivan** [comment]
Остальное исправил?

**Comment by Ilyanski** [comment]
Да исправил, лучше конф. скину что бы вдруг не обмануть. 
[23.11.17.zip](https://github.com/nmivan/Ilya_learning/files/1498090/23.11.17.zip)

**Comment by nmivan** [comment]
Приходные движения в перемещении так делать не стоит. Ты просто код расходных движений скопировал. В реальных условиях это будет падение производительности вдвое.

Подумай, как это сделать проще.

**Comment by Ilyanski** [comment]
Все сделал. 
[23,11,17.zip](https://github.com/nmivan/Ilya_learning/files/1498488/23.11.17.zip)
