### ISSUE TITLE
Развернуть локально заказ дилера и CouchDB

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#26]
Должно появиться:
1. Заказ дилера;
2. CouchDB с базами;
3. Связь CouchDB и заказа дилера.

**Comment by Ilyanski** [comment]
Проблема оказалась в том что в CouchDB не выполнил до конца установку, там нужно было выбрать сингл мод для моей задачи в закладке Setup. 
![image](https://user-images.githubusercontent.com/28789104/33647382-bbef7766-da76-11e7-849f-80d481bdfabf.png)

**Comment by Ilyanski** [comment]
все работает, задачу закрыть можно.
