### ISSUE TITLE
Номенклатура + отчет

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#4]
1. Создать иерархический справочник Номенклатура, иерархия групп и элементов;
2. Реквизиты номенклатуры - вес в кг, длина в мм, ширина в мм, площадь в мм2;
3. При записи номенклатуры площадь должна пересчитываться;
4. Сделать отчет по номенклатуре, который будет выводить все реквизиты.
На форме отчета должны быть отборы:
а. по весу;
б. по длине;
в. по площади.

**Comment by Ilyanski** [comment]
Задание выполнил, отбор можно выбирать меньше или равно, больше или равно. Ну мне удобно.
