### ISSUE TITLE
Контрагенты + Взаиморасчеты

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#6]
1. Добавить справочник Контрагенты
2. В документах Приход и Расход добавить реквизит шапки Контрагент;
3. В табличные части документов Приход и Расход добавить поля Цена и Сумма. В формах документов сделать пересчет суммы при изменении цены или количества;
4. Добавить остаточный регистр накопления "Взаиморасчеты", измерение Контрагент, ресурс Сумма. Документ Приход делает расход по регистру, документ Расход делает приход по регистру;
5. Сделать отчет "Взаиморасчеты", в котором будут выводиться в разрезе контрагентов остатки и обороты по суммам из регистра "Взаиморасчеты".

**Comment by Ilyanski** [comment]
Сделал, в моей случае остаток же только в отчете, ничего  такого сложного, в общем готов к продолжению.
