### ISSUE TITLE
Оплаты

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#7]
1. Добавить документ "Оплата поставщику". Указываем контрагента, сумму, делает движения по взаиморасчетам в плюс;
2. Добавить документ "Оплата от покупателя". Указываем контрагента, сумму, делает движения по взаиморасчетам в минус;
3. Добавить остаточный регистр накопления "Денежные средства", по нему движутся оба документа оплат. Оплата поставщику - в минус, оплата от покупателя - в плюс;
4. Сделать отчет по денежным средствам (нач.остаток, приход, расход, конечный остаток).

**Comment by Ilyanski** [comment]
Сделал, по двум документам, но старые документы приход, расход, не совсем понимаю как прикрепить туда.
