### ISSUE TITLE
Перемещение товаров

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#8]
1. Создать документ Перемещение товаров;
2. В шапке Склад-отправитель и Склад-получатель;
3. Табличная часть "Товары", в ней Номенклатура и Количество;
4. Документ двигается по регистру товаров, делая по каждой строке товаров два движения:
 - расход по складу-отправителю;
 - приход по складу-получателю.

**Comment by Ilyanski** [comment]
Задачу выполнил.
