### ISSUE TITLE
Контроль остатков товаров

### ISSUE THREAD

**Issue by nmivan** [nmivan/Ilya_learning#9]
Сделать так, чтобы при проведении документов Перемещение товаров и Расход осуществлялся контроль остатков товаров. Если какого-то товара не хватает, то документ не должен проводиться.

Должно выдаваться сообщение с номенклатурой, которой не хватает, запрошенным количеством и недостающим количеством.

Контроль должен лежать в общем модуле, и обслуживать оба документа.

**Comment by Ilyanski** [comment]
Не получается как то, спрашивал Евгения, он сказал передавать в общий модуль всю табличную часть и там ее перебирать в цикле, кароче если я сейчас это начну делать то я точно не успею закончить за сегодня, как мне кажется, ну или до смерти задолбаю его вопросами и сделаю)

**Comment by nmivan** [comment]
> Не получается как то

Так и должно быть, это сложная задача.

> если я сейчас это начну делать то я точно не успею закончить за сегодня

это не страшно, значит не получится самой эффективной недели.

**Comment by nmivan** [comment]
Илья, я сегодня дома.

Как дела по задаче?

Когда закончишь, приложи сюда конфигурацию (меню Конфигурация - Сохранить конфигурацию в файл).

**Comment by Ilyanski** [comment]
Документ Расходы плохо работает, пытаюсь понять почему. Я по отчету ориентируюсь о наличии Товаров на складе, на малом складе лежит 2500 Большой плитки, я ее продать пытаюсь, у меня ошибка проведения возникает.
ПеремещенияТоваров в свою очередь хорошо работают. Загрузил Табличную Часть в Таблицу Значений и сделал свертку, в этом плане все отлично. 
Осталось:
1) Решить проблему с Расходом.
2) Присобачить сообщение пользователю, тоже пока не могу представить как в сообщение недостающую номенклатуру приделать. 
Надеюсь все сегодня успею, тоже пораньше уйду.

**Comment by Ilyanski** [comment]
Проблемы в коде, я криво написал. Если вдруг окажется что последняя в списке номенклатура присутствует на складе, а все предыдущие отсутствовали, он ведь все равно будет передавать результат последней номенклатуры которая в наличии. И в минус может увести на складе, думаю как то надо от этого играть, задать что при наличии отрицательного количества он останавливался.

**Comment by Ilyanski** [comment]
Времени совсем нет уже, создал переменную "Херня" которая запоминает кол. строк после свертки в ТЗ которая ТабличнаяЧасть документа, потом еще одну переменную ввел "Хурня" она = 0, но по пути цикла считает разы когда выполняется условие Если, в конце если переменная Херня = Хурне, то возвращаю Отказ = ложь. По идее решил проблему, но при переводе какая то херня с числами, нет времени разобраться может мне и показалось.  
[27.09.17.zip](https://github.com/nmivan/Ilya_learning/files/1336216/27.09.17.zip)

**Comment by nmivan** [comment]
Конфигурация далека от совершенства, доделывай в соответствии с заданием.

**Comment by Ilyanski** [comment]
Доработал код, избавился от складов, сделал сообщения.
Решал проблему с отсутствием строк с помощью создания еще одного цикла, и вводом переменных, совсем не по пацански, проблему решало только в частных случаях. Я не понимаю даже что я должен сделать с этими Таблицами Значений что бы данную проблему решить.
[29.09.17.zip](https://github.com/nmivan/Ilya_learning/files/1344395/29.09.17.zip)

**Comment by nmivan** [comment]
По итогу-то не работает ведь для номенклатур, которых нет на складе вообще?
Давай думай, совсем чуть-чуть осталось.
И у тебя в перемещении реквизит называется Склад, а должен СкладОтправитель. Ты исправил название, чтобы функция контроля остатков работала? Сделать так, чтобы она работала на разных именах склада - часть задачи, так что переименовывай обратно.

**Comment by Ilyanski** [comment]
[02,10,17.zip](https://github.com/nmivan/Ilya_learning/files/1348857/02.10.17.zip)
